<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.329">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yufan Gong (UID: 305301666)">
<meta name="dcterms.date" content="2023-02-14">

<title>Biostat 203B Homework 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="hw2_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw2_files/libs/quarto-html/quarto.js"></script>
<script src="hw2_files/libs/quarto-html/popper.min.js"></script>
<script src="hw2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw2_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table" id="toc-q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table" class="nav-link active" data-scroll-target="#q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table"><span class="toc-section-number">1</span>  Q1. <code>read.csv</code> (base R) vs <code>read_csv</code> (tidyverse) vs <code>fread</code> (data.table)</a></li>
  <li><a href="#q2.-icu-stays" id="toc-q2.-icu-stays" class="nav-link" data-scroll-target="#q2.-icu-stays"><span class="toc-section-number">2</span>  Q2. ICU stays</a></li>
  <li><a href="#q3.-admission-data" id="toc-q3.-admission-data" class="nav-link" data-scroll-target="#q3.-admission-data"><span class="toc-section-number">3</span>  Q3. <code>admission</code> data</a></li>
  <li><a href="#q4.-patients-data" id="toc-q4.-patients-data" class="nav-link" data-scroll-target="#q4.-patients-data"><span class="toc-section-number">4</span>  Q4. <code>patients</code> data</a></li>
  <li><a href="#q5.-lab-results" id="toc-q5.-lab-results" class="nav-link" data-scroll-target="#q5.-lab-results"><span class="toc-section-number">5</span>  Q5. Lab results</a></li>
  <li><a href="#q6.-vitals-from-charted-events" id="toc-q6.-vitals-from-charted-events" class="nav-link" data-scroll-target="#q6.-vitals-from-charted-events"><span class="toc-section-number">6</span>  Q6. Vitals from charted events</a></li>
  <li><a href="#q7.-putting-things-together" id="toc-q7.-putting-things-together" class="nav-link" data-scroll-target="#q7.-putting-things-together"><span class="toc-section-number">7</span>  Q7. Putting things together</a></li>
  <li><a href="#q8.-exploratory-data-analysis-eda" id="toc-q8.-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#q8.-exploratory-data-analysis-eda"><span class="toc-section-number">8</span>  Q8. Exploratory data analysis (EDA)</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biostat 203B Homework 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yufan Gong (UID: 305301666) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 14, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>Display machine information for reproducibility:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] htmlwidgets_1.6.1 compiler_4.2.2    fastmap_1.1.0     cli_3.6.0        
 [5] tools_4.2.2       htmltools_0.5.4   rstudioapi_0.14   yaml_2.3.7       
 [9] rmarkdown_2.20    knitr_1.42        xfun_0.37         digest_0.6.31    
[13] jsonlite_1.8.4    rlang_1.0.6       evaluate_0.20    </code></pre>
</div>
</div>
<p>Load necessary libraries (you can add more as needed).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(R.utils)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>MIMIC data location</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mimic_path <span class="ot">&lt;-</span> <span class="st">"~/mimic"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this exercise, we use tidyverse (ggplot2, dplyr, etc) to explore the <a href="https://mimic.mit.edu/docs/iv/">MIMIC-IV</a> data introduced in <a href="https://ucla-biostat-203b.github.io/2023winter/hw/hw1/hw1.html">homework 1</a> and to build a cohort of ICU stays.</p>
<p>Display the contents of MIMIC data folder.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="st">"/"</span>, <span class="st">"/core"</span>, <span class="st">"/hosp"</span>, <span class="st">"/icu"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_names</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(<span class="sc">~</span><span class="fu">str_c</span>(<span class="st">"ls -l "</span>, mimic_path, .x) <span class="sc">%&gt;%</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">system</span>(<span class="at">intern =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>      )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`/`
[1] "total 40"                                                                  
[2] "-rw-rw-r--@ 1 yufangong  staff  2518 Mar 10  2021 LICENSE.txt"             
[3] "drwxr-xr-x@ 0 yufangong  staff     0 Jan 13 14:47 MIMIC-reduce-chartevents"
[4] "-rw-rw-r--@ 1 yufangong  staff  2459 Mar 16  2021 SHA256SUMS.txt"          
[5] "drwxr-xr-x@ 0 yufangong  staff     0 Jan 13 14:47 core"                    
[6] "drwxr-xr-x@ 0 yufangong  staff  4096 Jan 13 14:47 hosp"                    
[7] "drwxr-xr-x@ 0 yufangong  staff  4096 Jan 13 14:47 icu"                     
[8] "-rw-rw-r--@ 1 yufangong  staff   797 Jan  4  2022 index.html"              

$`/core`
[1] "total 142944"                                                           
[2] "-rw-rw-r--@ 1 yufangong  staff  17208966 Mar 15  2021 admissions.csv.gz"
[3] "-rw-rw-r--@ 1 yufangong  staff       606 Jan  4  2022 index.html"       
[4] "-rw-rw-r--@ 1 yufangong  staff   2955582 Mar 15  2021 patients.csv.gz"  
[5] "-rw-rw-r--@ 1 yufangong  staff  53014503 Mar 15  2021 transfers.csv.gz" 

$`/hosp`
 [1] "total 9243184"                                                                           
 [2] "-rw-rw-r--@ 1 yufangong  staff      430049 Mar 15  2021 d_hcpcs.csv.gz"                  
 [3] "-rw-rw-r--@ 1 yufangong  staff      863239 Mar 15  2021 d_icd_diagnoses.csv.gz"          
 [4] "-rw-rw-r--@ 1 yufangong  staff      579998 Mar 15  2021 d_icd_procedures.csv.gz"         
 [5] "-rw-rw-r--@ 1 yufangong  staff       14898 Mar 15  2021 d_labitems.csv.gz"               
 [6] "-rw-rw-r--@ 1 yufangong  staff    29531152 Mar 15  2021 diagnoses_icd.csv.gz"            
 [7] "-rw-rw-r--@ 1 yufangong  staff    11684062 Mar 15  2021 drgcodes.csv.gz"                 
 [8] "-rw-rw-r--@ 1 yufangong  staff   515763427 Mar 15  2021 emar.csv.gz"                     
 [9] "-rw-rw-r--@ 1 yufangong  staff   476252563 Mar 15  2021 emar_detail.csv.gz"              
[10] "-rw-rw-r--@ 1 yufangong  staff     2098831 Mar 15  2021 hcpcsevents.csv.gz"              
[11] "-rw-rw-r--@ 1 yufangong  staff        2325 Jan  4  2022 index.html"                      
[12] "-rw-rw-r--@ 1 yufangong  staff  2091865786 Mar 15  2021 labevents.csv.gz"                
[13] "-rw-rw-r--@ 1 yufangong  staff   171624288 Jan 27  2022 labevents_filtered_itemid.csv.gz"
[14] "-rw-rw-r--@ 1 yufangong  staff    99133381 Mar 15  2021 microbiologyevents.csv.gz"       
[15] "-rw-rw-r--@ 1 yufangong  staff   422874088 Mar 15  2021 pharmacy.csv.gz"                 
[16] "-rw-rw-r--@ 1 yufangong  staff   501381155 Mar 15  2021 poe.csv.gz"                      
[17] "-rw-rw-r--@ 1 yufangong  staff    24020923 Mar 15  2021 poe_detail.csv.gz"               
[18] "-rw-rw-r--@ 1 yufangong  staff   367041717 Mar 15  2021 prescriptions.csv.gz"            
[19] "-rw-rw-r--@ 1 yufangong  staff     7750325 Mar 15  2021 procedures_icd.csv.gz"           
[20] "-rw-rw-r--@ 1 yufangong  staff     9565293 Mar 15  2021 services.csv.gz"                 

$`/icu`
 [1] "total 5698008"                                                                             
 [2] "-rw-rw-r--@ 1 yufangong  staff  2350783547 Mar 15  2021 chartevents.csv.gz"                
 [3] "-rw-rw-r--@ 1 yufangong  staff   110272408 Jan 27  2022 chartevents_filtered_itemid.csv.gz"
 [4] "-rw-rw-r--@ 1 yufangong  staff       55917 Mar 15  2021 d_items.csv.gz"                    
 [5] "-rw-rw-r--@ 1 yufangong  staff    43296273 Mar 15  2021 datetimeevents.csv.gz"             
 [6] "-rw-rw-r--@ 1 yufangong  staff     2848628 Mar 15  2021 icustays.csv.gz"                   
 [7] "-rw-rw-r--@ 1 yufangong  staff        1103 Jan  4  2022 index.html"                        
 [8] "-rw-rw-r--@ 1 yufangong  staff   352443512 Mar 15  2021 inputevents.csv.gz"                
 [9] "-rw-rw-r--@ 1 yufangong  staff    37095672 Mar 15  2021 outputevents.csv.gz"               
[10] "-rw-rw-r--@ 1 yufangong  staff    20567368 Mar 15  2021 procedureevents.csv.gz"            </code></pre>
</div>
</div>
<section id="q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table"><span class="header-section-number">1</span> Q1. <code>read.csv</code> (base R) vs <code>read_csv</code> (tidyverse) vs <code>fread</code> (data.table)</h2>
<p>There are quite a few utilities in R for reading plain text data files. Let us test the speed of reading a moderate sized compressed csv file, <code>admissions.csv.gz</code>, by three programs: <code>read.csv</code> in base R, <code>read_csv</code> in tidyverse, and <code>fread</code> in the popular data.table package.</p>
<p>Which function is fastest? Is there difference in the (default) parsed data types? (Hint: R function <code>system.time</code> measures run times.)</p>
<p>For later questions, we stick to the <code>read_csv</code> in tidyverse.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(read.csv, read_csv, fread) <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span><span class="fu">system.time</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_c</span>(mimic_path, <span class="st">"/core"</span>, <span class="st">"/admissions.csv.gz"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        . <span class="sc">%&gt;%</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">map</span>(class) <span class="sc">%&gt;%</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>        <span class="fu">t</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">print</span>()</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_names</span>(<span class="st">"read.csv"</span>, <span class="st">"read_csv"</span>, <span class="st">"fread"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     [,1]       
subject_id           "integer"  
hadm_id              "integer"  
admittime            "character"
dischtime            "character"
deathtime            "character"
admission_type       "character"
admission_location   "character"
discharge_location   "character"
insurance            "character"
language             "character"
marital_status       "character"
ethnicity            "character"
edregtime            "character"
edouttime            "character"
hospital_expire_flag "integer"  
                     [,1]        [,2]       
subject_id           "numeric"   "numeric"  
hadm_id              "numeric"   "numeric"  
admittime            "POSIXct"   "POSIXt"   
dischtime            "POSIXct"   "POSIXt"   
deathtime            "POSIXct"   "POSIXt"   
admission_type       "character" "character"
admission_location   "character" "character"
discharge_location   "character" "character"
insurance            "character" "character"
language             "character" "character"
marital_status       "character" "character"
ethnicity            "character" "character"
edregtime            "POSIXct"   "POSIXt"   
edouttime            "POSIXct"   "POSIXt"   
hospital_expire_flag "numeric"   "numeric"  
                     [,1]        [,2]       
subject_id           "integer"   "integer"  
hadm_id              "integer"   "integer"  
admittime            "POSIXct"   "POSIXt"   
dischtime            "POSIXct"   "POSIXt"   
deathtime            "POSIXct"   "POSIXt"   
admission_type       "character" "character"
admission_location   "character" "character"
discharge_location   "character" "character"
insurance            "character" "character"
language             "character" "character"
marital_status       "character" "character"
ethnicity            "character" "character"
edregtime            "POSIXct"   "POSIXt"   
edouttime            "POSIXct"   "POSIXt"   
hospital_expire_flag "integer"   "integer"  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$read.csv
   user  system elapsed 
  5.075   0.117   5.199 

$read_csv
   user  system elapsed 
  1.648   1.684   0.749 

$fread
   user  system elapsed 
  0.391   0.103   0.496 </code></pre>
</div>
</div>
<p>It seems like <code>fread</code> is the fastest way to read a compressed csv file. The default data types are different between the three methods. In <code>read.csv</code> and <code>fread</code>, all numeric variables were classified as integer, while they remained numeric in <code>read_csv</code>. All date variables were classified as character in <code>read.csv</code>, while they remained as date format in <code>read_csv</code> and <code>fread</code>.</p>
</section>
<section id="q2.-icu-stays" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="q2.-icu-stays"><span class="header-section-number">2</span> Q2. ICU stays</h2>
<p><code>icustays.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/icu/icustays/" class="uri">https://mimic.mit.edu/docs/iv/modules/icu/icustays/</a>) contains data about Intensive Care Units (ICU) stays. The first 10 lines are</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/icustays.csv.gz"</span>), </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los"                                                    
 [2] "17867402,24528534,31793211,Trauma SICU (TSICU),Trauma SICU (TSICU),2154-03-03 04:11:00,2154-03-04 18:16:56,1.5874537037037035" 
 [3] "14435996,28960964,31983544,Trauma SICU (TSICU),Trauma SICU (TSICU),2150-06-19 17:57:00,2150-06-22 18:33:54,3.025625"           
 [4] "17609946,27385897,33183475,Trauma SICU (TSICU),Trauma SICU (TSICU),2138-02-05 18:54:00,2138-02-15 12:42:05,9.741724537037038"  
 [5] "18966770,23483021,34131444,Trauma SICU (TSICU),Trauma SICU (TSICU),2123-10-25 10:35:00,2123-10-25 18:59:47,0.35054398148148147"
 [6] "12776735,20817525,34547665,Neuro Stepdown,Neuro Stepdown,2200-07-12 00:33:00,2200-07-13 16:44:40,1.6747685185185184"           
 [7] "10215159,24283593,34569476,Trauma SICU (TSICU),Trauma SICU (TSICU),2124-09-20 15:05:29,2124-09-21 22:06:58,1.2926967592592593" 
 [8] "14489052,26516390,35056286,Trauma SICU (TSICU),Trauma SICU (TSICU),2118-10-26 10:33:56,2118-10-26 20:28:10,0.4126620370370371" 
 [9] "15914763,28906020,36909804,Trauma SICU (TSICU),Trauma SICU (TSICU),2176-12-14 12:00:00,2176-12-17 11:47:01,2.9909837962962964" 
[10] "16256226,20013290,39289362,Neuro Stepdown,Neuro Stepdown,2150-12-20 16:09:08,2150-12-21 14:58:40,0.9510648148148149"           </code></pre>
</div>
</div>
<ol type="1">
<li>Import <code>icustatys.csv.gz</code> as a tibble <code>icustays_tble</code>.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>icustays_tble <span class="ot">&lt;-</span> <span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/icustays.csv.gz"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 76,540 × 8
   subject_id  hadm_id  stay_id first_careunit          
        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;                   
 1   17867402 24528534 31793211 Trauma SICU (TSICU)     
 2   14435996 28960964 31983544 Trauma SICU (TSICU)     
 3   17609946 27385897 33183475 Trauma SICU (TSICU)     
 4   18966770 23483021 34131444 Trauma SICU (TSICU)     
 5   12776735 20817525 34547665 Neuro Stepdown          
 6   10215159 24283593 34569476 Trauma SICU (TSICU)     
 7   14489052 26516390 35056286 Trauma SICU (TSICU)     
 8   15914763 28906020 36909804 Trauma SICU (TSICU)     
 9   16256226 20013290 39289362 Neuro Stepdown          
10   19194449 21641999 39387567 Coronary Care Unit (CCU)
   last_careunit            intime              outtime               los
   &lt;chr&gt;                    &lt;dttm&gt;              &lt;dttm&gt;              &lt;dbl&gt;
 1 Trauma SICU (TSICU)      2154-03-03 04:11:00 2154-03-04 18:16:56 1.59 
 2 Trauma SICU (TSICU)      2150-06-19 17:57:00 2150-06-22 18:33:54 3.03 
 3 Trauma SICU (TSICU)      2138-02-05 18:54:00 2138-02-15 12:42:05 9.74 
 4 Trauma SICU (TSICU)      2123-10-25 10:35:00 2123-10-25 18:59:47 0.351
 5 Neuro Stepdown           2200-07-12 00:33:00 2200-07-13 16:44:40 1.67 
 6 Trauma SICU (TSICU)      2124-09-20 15:05:29 2124-09-21 22:06:58 1.29 
 7 Trauma SICU (TSICU)      2118-10-26 10:33:56 2118-10-26 20:28:10 0.413
 8 Trauma SICU (TSICU)      2176-12-14 12:00:00 2176-12-17 11:47:01 2.99 
 9 Neuro Stepdown           2150-12-20 16:09:08 2150-12-21 14:58:40 0.951
10 Coronary Care Unit (CCU) 2123-11-12 02:53:35 2123-11-12 13:52:03 0.457
# … with 76,530 more rows</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>How many unique <code>subject_id</code>? Can a <code>subject_id</code> have multiple ICU stays?</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>icustays_tble <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subject_id) <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53150</code></pre>
</div>
</div>
<p>There are 53150 unique <code>subject_id</code>. Yes, one <code>subject_id</code> can have multiple ICU stays.</p>
<ol start="3" type="1">
<li>Summarize the number of ICU stays per <code>subject_id</code> by graphs.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>icustays_tble <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id) <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">count =</span> <span class="fu">n</span>(), </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"keep"</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> count)) <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of ICU stays"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of subjects"</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="1">
<li>For each <code>subject_id</code>, let’s only keep the first ICU stay in the tibble <code>icustays_tble</code>. (Hint: <code>slice_min</code> and <code>slice_max</code> may take long. Think alternative ways to achieve the same function.)</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>icustays_tble <span class="ot">&lt;-</span> icustays_tble <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(intime, <span class="at">.by_group =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,150 × 8
   subject_id  hadm_id  stay_id first_careunit                                  
        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;                                           
 1   10000032 29079034 39553978 Medical Intensive Care Unit (MICU)              
 2   10000980 26913865 39765666 Medical Intensive Care Unit (MICU)              
 3   10001217 24597018 37067082 Surgical Intensive Care Unit (SICU)             
 4   10001725 25563031 31205490 Medical/Surgical Intensive Care Unit (MICU/SICU)
 5   10001884 26184834 37510196 Medical Intensive Care Unit (MICU)              
 6   10002013 23581541 39060235 Cardiac Vascular Intensive Care Unit (CVICU)    
 7   10002155 23822395 33685454 Coronary Care Unit (CCU)                        
 8   10002223 22494570 39638202 Trauma SICU (TSICU)                             
 9   10002348 22725460 32610785 Neuro Intermediate                              
10   10002428 28662225 33987268 Medical Intensive Care Unit (MICU)              
   last_careunit                                    intime             
   &lt;chr&gt;                                            &lt;dttm&gt;             
 1 Medical Intensive Care Unit (MICU)               2180-07-23 14:00:00
 2 Medical Intensive Care Unit (MICU)               2189-06-27 08:42:00
 3 Surgical Intensive Care Unit (SICU)              2157-11-20 19:18:02
 4 Medical/Surgical Intensive Care Unit (MICU/SICU) 2110-04-11 15:52:22
 5 Medical Intensive Care Unit (MICU)               2131-01-11 04:20:05
 6 Cardiac Vascular Intensive Care Unit (CVICU)     2160-05-18 10:00:53
 7 Coronary Care Unit (CCU)                         2129-08-04 12:45:00
 8 Trauma SICU (TSICU)                              2158-01-15 08:01:49
 9 Neuro Intermediate                               2112-11-30 23:24:00
10 Medical Intensive Care Unit (MICU)               2156-04-12 16:24:18
   outtime               los
   &lt;dttm&gt;              &lt;dbl&gt;
 1 2180-07-23 23:50:47 0.410
 2 2189-06-27 20:38:27 0.498
 3 2157-11-21 22:08:00 1.12 
 4 2110-04-12 23:59:56 1.34 
 5 2131-01-20 08:27:30 9.17 
 6 2160-05-19 17:33:33 1.31 
 7 2129-08-10 17:02:38 6.18 
 8 2158-01-16 15:19:24 1.30 
 9 2112-12-10 18:25:13 9.79 
10 2156-04-17 15:57:08 4.98 
# … with 53,140 more rows</code></pre>
</div>
</div>
</section>
<section id="q3.-admission-data" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="q3.-admission-data"><span class="header-section-number">3</span> Q3. <code>admission</code> data</h2>
<p>Information of the patients admitted into hospital is available in <code>admissions.csv.gz</code>. See <a href="https://mimic.mit.edu/docs/iv/modules/core/admissions/" class="uri">https://mimic.mit.edu/docs/iv/modules/core/admissions/</a> for details of each field in this file. The first 10 lines are</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/core/admissions.csv.gz"</span>), </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,marital_status,ethnicity,edregtime,edouttime,hospital_expire_flag"
 [2] "14679932,21038362,2139-09-26 14:16:00,2139-09-28 11:30:00,,ELECTIVE,,HOME,Other,ENGLISH,SINGLE,UNKNOWN,,,0"                                                                                
 [3] "15585972,24941086,2123-10-07 23:56:00,2123-10-12 11:22:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        
 [4] "11989120,21965160,2147-01-14 09:00:00,2147-01-17 14:25:00,,ELECTIVE,,HOME,Other,ENGLISH,,UNKNOWN,,,0"                                                                                      
 [5] "17817079,24709883,2165-12-27 17:33:00,2165-12-31 21:18:00,,ELECTIVE,,HOME,Other,ENGLISH,,OTHER,,,0"                                                                                        
 [6] "15078341,23272159,2122-08-28 08:48:00,2122-08-30 12:32:00,,ELECTIVE,,HOME,Other,ENGLISH,,BLACK/AFRICAN AMERICAN,,,0"                                                                       
 [7] "19124609,20517215,2169-03-14 12:44:00,2169-03-20 19:15:00,,ELECTIVE,,HOME,Other,ENGLISH,,UNKNOWN,,,0"                                                                                      
 [8] "17301855,29732723,2140-06-06 14:23:00,2140-06-08 14:25:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        
 [9] "17991012,24298836,2181-07-10 20:28:00,2181-07-12 15:49:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        
[10] "16865435,23216961,2185-07-19 02:12:00,2185-07-21 11:50:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        </code></pre>
</div>
</div>
<ol type="1">
<li>Import <code>admissions.csv.gz</code> as a tibble <code>admissions_tble</code>.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>admissions_tble <span class="ot">&lt;-</span> <span class="fu">str_c</span>(mimic_path, <span class="st">"/core/admissions.csv.gz"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 523,740 × 15
   subject_id  hadm_id admittime           dischtime           deathtime
        &lt;dbl&gt;    &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;              &lt;dttm&gt;   
 1   14679932 21038362 2139-09-26 14:16:00 2139-09-28 11:30:00 NA       
 2   15585972 24941086 2123-10-07 23:56:00 2123-10-12 11:22:00 NA       
 3   11989120 21965160 2147-01-14 09:00:00 2147-01-17 14:25:00 NA       
 4   17817079 24709883 2165-12-27 17:33:00 2165-12-31 21:18:00 NA       
 5   15078341 23272159 2122-08-28 08:48:00 2122-08-30 12:32:00 NA       
 6   19124609 20517215 2169-03-14 12:44:00 2169-03-20 19:15:00 NA       
 7   17301855 29732723 2140-06-06 14:23:00 2140-06-08 14:25:00 NA       
 8   17991012 24298836 2181-07-10 20:28:00 2181-07-12 15:49:00 NA       
 9   16865435 23216961 2185-07-19 02:12:00 2185-07-21 11:50:00 NA       
10   13693648 21640725 2111-01-30 23:43:00 2111-02-02 13:03:00 NA       
   admission_type admission_location discharge_location insurance language
   &lt;chr&gt;          &lt;chr&gt;              &lt;chr&gt;              &lt;chr&gt;     &lt;chr&gt;   
 1 ELECTIVE       &lt;NA&gt;               HOME               Other     ENGLISH 
 2 ELECTIVE       &lt;NA&gt;               HOME               Other     ENGLISH 
 3 ELECTIVE       &lt;NA&gt;               HOME               Other     ENGLISH 
 4 ELECTIVE       &lt;NA&gt;               HOME               Other     ENGLISH 
 5 ELECTIVE       &lt;NA&gt;               HOME               Other     ENGLISH 
 6 ELECTIVE       &lt;NA&gt;               HOME               Other     ENGLISH 
 7 ELECTIVE       &lt;NA&gt;               HOME               Other     ENGLISH 
 8 ELECTIVE       &lt;NA&gt;               HOME               Other     ENGLISH 
 9 ELECTIVE       &lt;NA&gt;               HOME               Other     ENGLISH 
10 ELECTIVE       &lt;NA&gt;               HOME               Other     ENGLISH 
   marital_status ethnicity              edregtime edouttime
   &lt;chr&gt;          &lt;chr&gt;                  &lt;dttm&gt;    &lt;dttm&gt;   
 1 SINGLE         UNKNOWN                NA        NA       
 2 &lt;NA&gt;           WHITE                  NA        NA       
 3 &lt;NA&gt;           UNKNOWN                NA        NA       
 4 &lt;NA&gt;           OTHER                  NA        NA       
 5 &lt;NA&gt;           BLACK/AFRICAN AMERICAN NA        NA       
 6 &lt;NA&gt;           UNKNOWN                NA        NA       
 7 &lt;NA&gt;           WHITE                  NA        NA       
 8 &lt;NA&gt;           WHITE                  NA        NA       
 9 &lt;NA&gt;           WHITE                  NA        NA       
10 &lt;NA&gt;           WHITE                  NA        NA       
   hospital_expire_flag
                  &lt;dbl&gt;
 1                    0
 2                    0
 3                    0
 4                    0
 5                    0
 6                    0
 7                    0
 8                    0
 9                    0
10                    0
# … with 523,730 more rows</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Let’s only keep the admissions that have a match in <code>icustays_tble</code> according to <code>subject_id</code> and <code>hadm_id</code>.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>admissions_tble <span class="ot">&lt;-</span> admissions_tble <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    icustays_tble, </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"subject_id"</span>, <span class="st">"hadm_id"</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>hadm_id) <span class="sc">%&gt;%</span> </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,150 × 14
   subject_id admittime           dischtime           deathtime          
        &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;              &lt;dttm&gt;             
 1   10222255 2120-11-20 20:25:00 2120-11-22 13:00:00 NA                 
 2   14485852 2113-10-31 00:23:00 2113-11-04 16:50:00 NA                 
 3   18709254 2195-10-12 01:31:00 2195-10-12 13:51:00 NA                 
 4   16837807 2151-03-19 06:09:00 2151-03-19 07:20:00 2151-03-19 07:20:00
 5   17642680 2116-05-29 12:48:00 2116-05-30 12:31:00 NA                 
 6   18230965 2142-03-12 20:00:00 2142-03-17 15:26:00 NA                 
 7   17374121 2115-07-22 07:15:00 2115-07-24 17:50:00 NA                 
 8   13346506 2181-11-19 14:32:00 2181-11-22 18:47:00 NA                 
 9   18030332 2152-07-22 21:28:00 2152-07-27 16:49:00 NA                 
10   14328744 2126-08-20 09:26:00 2126-08-21 11:36:00 NA                 
   admission_type     admission_location     discharge_location insurance
   &lt;chr&gt;              &lt;chr&gt;                  &lt;chr&gt;              &lt;chr&gt;    
 1 EU OBSERVATION     TRANSFER FROM HOSPITAL &lt;NA&gt;               Other    
 2 EW EMER.           EMERGENCY ROOM         &lt;NA&gt;               Other    
 3 EU OBSERVATION     EMERGENCY ROOM         &lt;NA&gt;               Medicaid 
 4 EU OBSERVATION     EMERGENCY ROOM         &lt;NA&gt;               Medicare 
 5 EU OBSERVATION     WALK-IN/SELF REFERRAL  &lt;NA&gt;               Other    
 6 URGENT             PHYSICIAN REFERRAL     HOME               Other    
 7 DIRECT OBSERVATION PHYSICIAN REFERRAL     &lt;NA&gt;               Other    
 8 EU OBSERVATION     EMERGENCY ROOM         &lt;NA&gt;               Other    
 9 URGENT             TRANSFER FROM HOSPITAL HOME               Other    
10 EU OBSERVATION     EMERGENCY ROOM         &lt;NA&gt;               Other    
   language marital_status ethnicity edregtime           edouttime          
   &lt;chr&gt;    &lt;chr&gt;          &lt;chr&gt;     &lt;dttm&gt;              &lt;dttm&gt;             
 1 ENGLISH  MARRIED        WHITE     2120-11-20 18:07:00 2120-11-21 20:25:00
 2 ENGLISH  SINGLE         WHITE     2113-10-30 19:48:00 2113-10-31 05:10:00
 3 ENGLISH  WIDOWED        ASIAN     2195-10-11 18:40:00 2195-10-12 02:47:00
 4 ENGLISH  SINGLE         WHITE     2151-03-19 02:55:00 2151-03-19 06:59:00
 5 ENGLISH  SINGLE         WHITE     2116-05-29 10:05:00 2116-05-30 01:17:00
 6 ENGLISH  MARRIED        WHITE     NA                  NA                 
 7 ENGLISH  MARRIED        WHITE     NA                  NA                 
 8 ENGLISH  MARRIED        WHITE     2181-11-19 10:51:00 2181-11-19 15:12:00
 9 ENGLISH  MARRIED        UNKNOWN   NA                  NA                 
10 ENGLISH  MARRIED        WHITE     2126-08-19 23:01:00 2126-08-20 10:14:00
   hospital_expire_flag
                  &lt;dbl&gt;
 1                    0
 2                    0
 3                    0
 4                    1
 5                    0
 6                    0
 7                    0
 8                    0
 9                    0
10                    0
# … with 53,140 more rows</code></pre>
</div>
</div>
<ol start="3" type="1">
<li><p>Summarize the following variables by graphics.</p>
<ul>
<li>admission year<br>
</li>
<li>admission month<br>
</li>
<li>admission month day<br>
</li>
<li>admission week day<br>
</li>
<li>admission hour (anything unusual?)<br>
</li>
<li>admission minute (anything unusual?)<br>
</li>
<li>length of hospital stay (anything unusual?)</li>
</ul></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(year, month, mday, wday, hour, minute),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"Year"</span>, <span class="st">"Month"</span>, <span class="st">"Month day"</span>, <span class="st">"Week day"</span>, <span class="st">"Hour"</span>, <span class="st">"Minute"</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pmap</span>(<span class="sc">~</span>admissions_tble <span class="sc">%&gt;%</span> </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>         <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> admittime <span class="sc">%&gt;%</span> </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                      .x)) <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>         <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>         <span class="fu">labs</span>(</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">x =</span> .y,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> <span class="st">"Number of subjects"</span>) <span class="sc">+</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>         <span class="fu">theme_classic</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[5]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-13-5.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[6]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-13-6.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>It seems like patients are more likely to be admitted after 3 p.m. and reach peak at 12 a.m. There is also a regional peak around 7 a.m.</p>
<p>It seems like there is a recurring peak of patient admission every 14 minutes.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>admissions_tble <span class="ot">&lt;-</span> admissions_tble <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">lengthstay =</span> <span class="fu">interval</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ymd_hms</span>(admittime), </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ymd_hms</span>(dischtime)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>      ) <span class="sc">%&gt;%</span> </span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.duration</span>()<span class="sc">/</span><span class="dv">3600</span><span class="sc">/</span><span class="dv">24</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    ) </span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>admissions_tble <span class="sc">%&gt;%</span> </span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> lengthstay)) <span class="sc">+</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">500</span>) <span class="sc">+</span> </span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Length of hospital stay (days)"</span>,</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of subjects"</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Most patients will be discharged within 20 days, however, there are a few of them stayed over 100 days.</p>
</section>
<section id="q4.-patients-data" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="q4.-patients-data"><span class="header-section-number">4</span> Q4. <code>patients</code> data</h2>
<p>Patient information is available in <code>patients.csv.gz</code>. See <a href="https://mimic.mit.edu/docs/iv/modules/core/patients/" class="uri">https://mimic.mit.edu/docs/iv/modules/core/patients/</a> for details of each field in this file. The first 10 lines are</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/core/patients.csv.gz"</span>), </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod"
 [2] "10000048,F,23,2126,2008 - 2010,"                               
 [3] "10002723,F,0,2128,2017 - 2019,"                                
 [4] "10003939,M,0,2184,2008 - 2010,"                                
 [5] "10004222,M,0,2161,2014 - 2016,"                                
 [6] "10005325,F,0,2154,2011 - 2013,"                                
 [7] "10007338,F,0,2153,2017 - 2019,"                                
 [8] "10008101,M,0,2142,2008 - 2010,"                                
 [9] "10009872,F,0,2168,2014 - 2016,"                                
[10] "10011333,F,0,2132,2014 - 2016,"                                </code></pre>
</div>
</div>
<ol type="1">
<li>Import <code>patients.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/core/patients/" class="uri">https://mimic.mit.edu/docs/iv/modules/core/patients/</a>) as a tibble <code>patients_tble</code> and only keep the patients who have a match in <code>icustays_tble</code> (according to <code>subject_id</code>).</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>patients_tble <span class="ot">&lt;-</span> <span class="fu">str_c</span>(mimic_path, <span class="st">"/core/patients.csv.gz"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    icustays_tble, </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"subject_id"</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">gender =</span> <span class="fu">case_when</span>(gender <span class="sc">==</span> <span class="st">"F"</span> <span class="sc">~</span> <span class="st">"Female"</span>, </span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>                       gender <span class="sc">==</span> <span class="st">"M"</span> <span class="sc">~</span> <span class="st">"Male"</span>, </span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>                       <span class="cn">TRUE</span> <span class="sc">~</span> gender</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,150 × 6
   subject_id gender anchor_age anchor_year anchor_year_group dod       
        &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;             &lt;date&gt;    
 1   10018928 Female         31        2125 2008 - 2010       NA        
 2   10076543 Female         78        2187 2008 - 2010       NA        
 3   10098428 Female         85        2119 2008 - 2010       NA        
 4   10127185 Male           60        2141 2008 - 2010       NA        
 5   10148710 Male           67        2137 2008 - 2010       NA        
 6   10156486 Female         75        2124 2017 - 2019       NA        
 7   10159585 Male           59        2146 2008 - 2010       2154-04-16
 8   10171525 Female         27        2115 2014 - 2016       NA        
 9   10196360 Male           57        2118 2011 - 2013       NA        
10   10227823 Male           45        2156 2014 - 2016       NA        
# … with 53,140 more rows</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Summarize variables <code>gender</code> and <code>anchor_age</code>, and explain any patterns you see.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>patients_tble <span class="sc">%&gt;%</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender) <span class="sc">%&gt;%</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> anchor_age)) <span class="sc">+</span> </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of subjects"</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>gender) <span class="sc">+</span> </span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>There are more males than females.</li>
<li>The age of most patients is between 50-80 in both males and females.</li>
<li>There are more patients in their 90s than any other age groups.</li>
</ul>
</section>
<section id="q5.-lab-results" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="q5.-lab-results"><span class="header-section-number">5</span> Q5. Lab results</h2>
<p><code>labevents.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/hosp/labevents/" class="uri">https://mimic.mit.edu/docs/iv/modules/hosp/labevents/</a>) contains all laboratory measurements for patients. The first 10 lines are</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/hosp/labevents.csv.gz"</span>), </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "labevent_id,subject_id,hadm_id,specimen_id,itemid,charttime,storetime,value,valuenum,valueuom,ref_range_lower,ref_range_upper,flag,priority,comments"
 [2] "670,10000048,,6448755,51484,2126-11-22 19:20:00,2126-11-22 20:07:00,150,150,mg/dL,,,,STAT,"                                                          
 [3] "673,10000048,,6448755,51491,2126-11-22 19:20:00,2126-11-22 20:07:00,6.5,6.5,units,5,8,,STAT,"                                                        
 [4] "675,10000048,,6448755,51498,2126-11-22 19:20:00,2126-11-22 20:07:00,1.029,1.029, ,1.001,1.035,,STAT,"                                                
 [5] "683,10000048,,82729055,50861,2126-11-22 20:45:00,2126-11-23 00:55:00,39,39,IU/L,0,40,,STAT,"                                                         
 [6] "684,10000048,,82729055,50862,2126-11-22 20:45:00,2126-11-23 00:55:00,4.7,4.7,g/dL,3.4,4.8,,STAT,"                                                    
 [7] "685,10000048,,82729055,50863,2126-11-22 20:45:00,2126-11-23 00:55:00,45,45,IU/L,39,117,,STAT,"                                                       
 [8] "686,10000048,,82729055,50868,2126-11-22 20:45:00,2126-11-22 21:32:00,13,13,mEq/L,8,20,,STAT,"                                                        
 [9] "687,10000048,,82729055,50878,2126-11-22 20:45:00,2126-11-23 00:55:00,28,28,IU/L,0,40,,STAT,"                                                         
[10] "688,10000048,,82729055,50882,2126-11-22 20:45:00,2126-11-22 21:32:00,26,26,mEq/L,22,32,,STAT,"                                                       </code></pre>
</div>
</div>
<p><code>d_labitems.csv.gz</code> is the dictionary of lab measurements.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/hosp/d_labitems.csv.gz"</span>), </span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "itemid,label,fluid,category,loinc_code"           
 [2] "51905, ,Other Body Fluid,Chemistry,"              
 [3] "51532,11-Deoxycorticosterone,Blood,Chemistry,"    
 [4] "51957,17-Hydroxycorticosteroids,Urine,Chemistry," 
 [5] "51958,\"17-Ketosteroids, Urine\",Urine,Chemistry,"
 [6] "52068,24 Hr,Blood,Hematology,"                    
 [7] "51066,24 hr Calcium,Urine,Chemistry,"             
 [8] "51067,24 hr Creatinine,Urine,Chemistry,"          
 [9] "51068,24 hr Protein,Urine,Chemistry,"             
[10] "50853,25-OH Vitamin D,Blood,Chemistry,"           </code></pre>
</div>
</div>
<ol type="1">
<li>Find how many rows are in <code>labevents.csv.gz</code>.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/hosp/labevents.csv.gz"</span>), </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | wc -l"</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] " 122103668"</code></pre>
</div>
</div>
<ol start="2" type="1">
<li><p>We are interested in the lab measurements of creatinine (50912), potassium (50971), sodium (50983), chloride (50902), bicarbonate (50882), hematocrit (51221), white blood cell count (51301), and glucose (50931). Retrieve a subset of <code>labevents.csv.gz</code> only containing these items for the patients in <code>icustays_tble</code> as a tibble <code>labevents_tble</code>.</p>
<p>Hint: <code>labevents.csv.gz</code> is a data file too big to be read in by the <code>read_csv</code> function in its default setting. Utilize the <code>col_select</code> option in the <code>read_csv</code> function to reduce the memory burden. It took my computer 5-10 minutes to ingest this file. If your computer really has trouble importing <code>labevents.csv.gz</code>, you can import from the reduced data file <code>labevents_filtered_itemid.csv.gz</code>.</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>dlabitems_tble <span class="ot">&lt;-</span> <span class="fu">str_c</span>(</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>    mimic_path, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"/hosp/d_labitems.csv.gz"</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(itemid <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">50912</span>, <span class="dv">50971</span>, <span class="dv">50983</span>, <span class="dv">50902</span>, </span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>                       <span class="dv">50882</span>, <span class="dv">51221</span>, <span class="dv">51301</span>, <span class="dv">50931</span>)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span> </span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  itemid label             fluid category   loinc_code
   &lt;dbl&gt; &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;     
1  50882 Bicarbonate       Blood Chemistry  1963-8    
2  50902 Chloride          Blood Chemistry  2075-0    
3  50912 Creatinine        Blood Chemistry  2160-0    
4  50931 Glucose           Blood Chemistry  6777-7    
5  51221 Hematocrit        Blood Hematology 4544-3    
6  50971 Potassium         Blood Chemistry  2823-3    
7  50983 Sodium            Blood Chemistry  2951-2    
8  51301 White Blood Cells Blood Hematology 804-5     </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>labevents_tble <span class="ot">&lt;-</span> </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    mimic_path, </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"/hosp/labevents_filtered_itemid.csv.gz"</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(itemid <span class="sc">%in%</span> dlabitems_tble<span class="sc">$</span>itemid) <span class="sc">%&gt;%</span> </span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    icustays_tble, </span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"subject_id"</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13,926,853 × 4
   subject_id itemid charttime           valuenum
        &lt;dbl&gt;  &lt;dbl&gt; &lt;dttm&gt;                 &lt;dbl&gt;
 1   10003700  50882 2162-11-15 17:00:00     27  
 2   10003700  50902 2162-11-15 17:00:00    103  
 3   10003700  50912 2162-11-15 17:00:00      1  
 4   10003700  50931 2162-11-15 17:00:00     93  
 5   10003700  50971 2162-11-15 17:00:00      4.1
 6   10003700  50983 2162-11-15 17:00:00    141  
 7   10003700  51221 2162-11-15 17:00:00     40  
 8   10003700  51301 2162-11-15 17:00:00      6.7
 9   10003700  51221 2165-04-24 03:40:00     41  
10   10003700  51301 2165-04-24 03:40:00      5.8
# … with 13,926,843 more rows</code></pre>
</div>
</div>
<p>I tried to load the data into my laptop, however, my R session aborted since it exceeded the memory limit (8G). Therefore, I loaded <code>labevents_filtered_itemid.csv.gz</code> here to save some memory space.</p>
<ol start="3" type="1">
<li>Further restrict <code>labevents_tble</code> to the first lab measurement during the ICU stay.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>labevents_tble <span class="ot">&lt;-</span> labevents_tble <span class="sc">%&gt;%</span> </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(icustays_tble <span class="sc">%&gt;%</span> </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">select</span>(subject_id, intime, outtime), </span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(charttime <span class="sc">&gt;=</span> intime <span class="sc">&amp;</span> charttime <span class="sc">&lt;=</span> outtime) <span class="sc">%&gt;%</span> </span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id, itemid) <span class="sc">%&gt;%</span> </span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(charttime, <span class="at">.by_group =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(intime, outtime, charttime)) <span class="sc">%&gt;%</span> </span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">id_cols =</span> subject_id, </span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> itemid,</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> valuenum</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_at</span>(</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">vars</span>(dlabitems_tble <span class="sc">%&gt;%</span> </span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>           <span class="fu">pull</span>(itemid) <span class="sc">%&gt;%</span> </span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>           <span class="fu">as.character</span>()</span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>         ), </span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span>dlabitems_tble <span class="sc">%&gt;%</span> </span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pull</span>(label) <span class="sc">%&gt;%</span> </span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_to_lower</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_replace_all</span>(<span class="st">" "</span>,<span class="st">"_"</span>)</span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 51,618 × 9
   subject_id bicarbonate chloride creatinine glucose potassium sodium
        &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
 1   10000032          21      102        0.5     115       4.7    132
 2   10001217          23      104        0.4     113       3.6    138
 3   10001725          24      106        0.8     146       3.9    140
 4   10001884          33       96        1.1     148       4      136
 5   10002013          23      109        1.1      98       4      140
 6   10002155          25      106        0.9      95       4.5    139
 7   10002223          26      102        0.8      88       3.9    138
 8   10002348          23      107        0.8     127       4.8    142
 9   10002428          20       98        0.8      99       3.9    129
10   10002430          22      105        2.2     128       3.8    144
   hematocrit white_blood_cells
        &lt;dbl&gt;             &lt;dbl&gt;
 1       NA                NA  
 2       33.6              19  
 3       39.1              17  
 4       36                18.4
 5       28.6              18.2
 6       37.9               5.5
 7       32.5              10.1
 8       39.3               4.3
 9       28.7              22.4
10       36.6              10.3
# … with 51,608 more rows</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Summarize the lab measurements by appropriate numerics and graphics.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>labevents_tble <span class="sc">%&gt;%</span> </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>subject_id) <span class="sc">%&gt;%</span> </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(summary) <span class="sc">%&gt;%</span> </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(<span class="at">.id =</span> <span class="st">"id"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 8
  id                Min.        `1st Qu.`   Median    Mean  3rd Q…¹ Max.  `NA's`
  &lt;chr&gt;             &lt;table[1d]&gt; &lt;table[1d]&gt; &lt;table[1&gt; &lt;tab&gt; &lt;table&gt; &lt;tab&gt; &lt;tabl&gt;
1 bicarbonate        2.0         21.0        23.0      22.…  25.0     49… 273   
2 chloride          58.0        101.0       105.0     104.… 108.0    153… 233   
3 creatinine         0.0          0.7         0.9       1.…   1.3     36… 252   
4 glucose            7.0        103.0       124.0     141.… 156.0   2440… 349   
5 potassium          0.8          3.7         4.1       4.…   4.5     13… 259   
6 sodium            92.0        136.0       139.0     138.… 141.0    180… 227   
7 hematocrit         4.3         28.1        32.6      32.…  37.3     68… 499   
8 white_blood_cells  0.0          7.6        10.6      12.…  14.5    572… 622   
# … with abbreviated variable name ¹​`3rd Qu.`</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>labevents_tble <span class="sc">%&gt;%</span> </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="sc">!</span>subject_id,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"lab_measure"</span>,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"value"</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lab_measure) <span class="sc">%&gt;%</span> </span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> lab_measure, <span class="at">y =</span> value, <span class="at">color =</span> lab_measure)) <span class="sc">+</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>, <span class="at">na.rm =</span> T, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">300</span>)) <span class="sc">+</span> </span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_colorblind</span>() <span class="sc">+</span> </span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Lab measurements"</span>,</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Value"</span>,</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Lab measurements "</span></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>I hid the outliers for each lab measurement and limit the <code>value</code> axis (300) so that the boxplots would not gather together.</p>
</section>
<section id="q6.-vitals-from-charted-events" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="q6.-vitals-from-charted-events"><span class="header-section-number">6</span> Q6. Vitals from charted events</h2>
<p><code>chartevents.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/icu/chartevents/" class="uri">https://mimic.mit.edu/docs/iv/modules/icu/chartevents/</a>) contains all the charted data available for a patient. During their ICU stay, the primary repository of a patient’s information is their electronic chart. The <code>itemid</code> variable indicates a single measurement type in the database. The <code>value</code> variable is the value measured for <code>itemid</code>. The first 10 lines of <code>chartevents.csv.gz</code> are</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/chartevents.csv.gz"</span>), </span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span>), </span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,hadm_id,stay_id,charttime,storetime,itemid,value,valuenum,valueuom,warning"
 [2] "10003700,28623837,30600691,2165-04-24 05:10:00,2165-04-24 05:11:00,228236,0,0,,0"     
 [3] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225067,0,0,,0"     
 [4] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225070,1,1,,0"     
 [5] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225076,1,1,,0"     
 [6] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225078,1,1,,0"     
 [7] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225086,1,1,,0"     
 [8] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225091,1,1,,0"     
 [9] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225103,1,1,,0"     
[10] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225106,1,1,,0"     </code></pre>
</div>
</div>
<p><code>d_items.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/icu/d_items/" class="uri">https://mimic.mit.edu/docs/iv/modules/icu/d_items/</a>) is the dictionary for the <code>itemid</code> in <code>chartevents.csv.gz</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/d_items.csv.gz"</span>), </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span>), </span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue"   
 [2] "220003,ICU Admission date,ICU Admission date,datetimeevents,ADT,,Date and time,,"                
 [3] "220045,Heart Rate,HR,chartevents,Routine Vital Signs,bpm,Numeric,,"                              
 [4] "220046,Heart rate Alarm - High,HR Alarm - High,chartevents,Alarms,bpm,Numeric,,"                 
 [5] "220047,Heart Rate Alarm - Low,HR Alarm - Low,chartevents,Alarms,bpm,Numeric,,"                   
 [6] "220048,Heart Rhythm,Heart Rhythm,chartevents,Routine Vital Signs,,Text,,"                        
 [7] "220050,Arterial Blood Pressure systolic,ABPs,chartevents,Routine Vital Signs,mmHg,Numeric,90,140"
 [8] "220051,Arterial Blood Pressure diastolic,ABPd,chartevents,Routine Vital Signs,mmHg,Numeric,60,90"
 [9] "220052,Arterial Blood Pressure mean,ABPm,chartevents,Routine Vital Signs,mmHg,Numeric,,"         
[10] "220056,Arterial Blood Pressure Alarm - Low,ABP Alarm - Low,chartevents,Alarms,mmHg,Numeric,,"    </code></pre>
</div>
</div>
<ol type="1">
<li><p>We are interested in the vitals for ICU patients: heart rate (220045), mean non-invasive blood pressure (220181), systolic non-invasive blood pressure (220179), body temperature in Fahrenheit (223761), and respiratory rate (220210). Retrieve a subset of <code>chartevents.csv.gz</code> only containing these items for the patients in <code>icustays_tble</code> as a tibble <code>chartevents_tble</code>.</p>
<p>Hint: <code>chartevents.csv.gz</code> is a data file too big to be read in by the <code>read_csv</code> function in its default setting. Utilize the <code>col_select</code> option in the <code>read_csv</code> function to reduce the memory burden. It took my computer &gt;15 minutes to ingest this file. If your computer really has trouble importing <code>labevents.csv.gz</code>, you can import from the reduced data file <code>chartevents_filtered_itemid.csv.gz</code>.</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>dchartitems_tble <span class="ot">&lt;-</span> <span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/d_items.csv.gz"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(itemid <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">220045</span>, <span class="dv">220181</span>, <span class="dv">220179</span>, <span class="dv">223761</span>, <span class="dv">220210</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 9
  itemid label                                abbreviation  linksto    
   &lt;dbl&gt; &lt;chr&gt;                                &lt;chr&gt;         &lt;chr&gt;      
1 220045 Heart Rate                           HR            chartevents
2 220179 Non Invasive Blood Pressure systolic NBPs          chartevents
3 220181 Non Invasive Blood Pressure mean     NBPm          chartevents
4 220210 Respiratory Rate                     RR            chartevents
5 223761 Temperature Fahrenheit               Temperature F chartevents
  category            unitname param_type lownormalvalue highnormalvalue
  &lt;chr&gt;               &lt;chr&gt;    &lt;chr&gt;               &lt;dbl&gt;           &lt;dbl&gt;
1 Routine Vital Signs bpm      Numeric                NA              NA
2 Routine Vital Signs mmHg     Numeric                NA              NA
3 Routine Vital Signs mmHg     Numeric                NA              NA
4 Respiratory         insp/min Numeric                NA              NA
5 Routine Vital Signs °F       Numeric                NA              NA</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>chartevents_tble <span class="ot">&lt;-</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>    mimic_path, </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"/icu/chartevents_filtered_itemid.csv.gz"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(itemid <span class="sc">%in%</span> dchartitems_tble<span class="sc">$</span>itemid) <span class="sc">%&gt;%</span> </span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>    icustays_tble, </span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"subject_id"</span>, <span class="st">"hadm_id"</span>, <span class="st">"stay_id"</span>)</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(hadm_id, stay_id)) <span class="sc">%&gt;%</span> </span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15,738,349 × 4
   subject_id charttime           itemid valuenum
        &lt;dbl&gt; &lt;dttm&gt;               &lt;dbl&gt;    &lt;dbl&gt;
 1   10003700 2165-04-24 05:28:00 220179    152  
 2   10003700 2165-04-24 05:28:00 220181    110  
 3   10003700 2165-04-24 05:30:00 220045     65  
 4   10003700 2165-04-24 05:30:00 220210     14  
 5   10003700 2165-04-24 05:38:00 223761     97.6
 6   10003700 2165-04-24 06:00:00 220045     56  
 7   10003700 2165-04-24 06:00:00 220179    126  
 8   10003700 2165-04-24 06:00:00 220181     88  
 9   10003700 2165-04-24 06:00:00 220210     14  
10   10003700 2165-04-24 06:09:00 220045     55  
# … with 15,738,339 more rows</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Further restrict <code>chartevents_tble</code> to the first vital measurement during the ICU stay.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>chartevents_tble <span class="ot">&lt;-</span> chartevents_tble <span class="sc">%&gt;%</span> </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(icustays_tble <span class="sc">%&gt;%</span> </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">select</span>(subject_id, intime, outtime), </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(charttime <span class="sc">&gt;=</span> intime <span class="sc">&amp;</span> charttime <span class="sc">&lt;=</span> outtime) <span class="sc">%&gt;%</span> </span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id, itemid) <span class="sc">%&gt;%</span> </span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(charttime, <span class="at">.by_group =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(intime, outtime, charttime)) <span class="sc">%&gt;%</span> </span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">id_cols =</span> subject_id, </span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> itemid,</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> valuenum</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_at</span>(</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">vars</span>(dchartitems_tble <span class="sc">%&gt;%</span> </span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>           <span class="fu">pull</span>(itemid) <span class="sc">%&gt;%</span> </span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>           <span class="fu">as.character</span>()</span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>         ), </span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span>dchartitems_tble <span class="sc">%&gt;%</span> </span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pull</span>(label) <span class="sc">%&gt;%</span> </span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_to_lower</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_replace_all</span>(<span class="st">" "</span>,<span class="st">"_"</span>)</span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,136 × 6
   subject_id heart_rate non_invasive_blood_pressure_systolic
        &lt;dbl&gt;      &lt;dbl&gt;                                &lt;dbl&gt;
 1   10000032         91                                   84
 2   10000980         77                                  150
 3   10001217         86                                  151
 4   10001725         55                                   73
 5   10001884         38                                  180
 6   10002013         80                                  104
 7   10002155         68                                  126
 8   10002223        100                                  123
 9   10002348         72                                  129
10   10002428        124                                   87
   non_invasive_blood_pressure_mean respiratory_rate temperature_fahrenheit
                              &lt;dbl&gt;            &lt;dbl&gt;                  &lt;dbl&gt;
 1                               56               24                   98.7
 2                               92               23                   98  
 3                              104               18                   98.5
 4                               59               19                   97.7
 5                               46               10                   98.1
 6                               77               14                   97.2
 7                               78               18                   95.9
 8                               80               29                   98.6
 9                               85               14                   97.9
10                               53               25                  103. 
# … with 53,126 more rows</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Summarize these vital measurements by appropriate numerics and graphics.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>chartevents_tble <span class="sc">%&gt;%</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>subject_id) <span class="sc">%&gt;%</span> </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(summary) <span class="sc">%&gt;%</span> </span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(<span class="at">.id =</span> <span class="st">"id"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 8
  id                             Min.  1st Q…¹ Median Mean  3rd Q…² Max.  `NA's`
  &lt;chr&gt;                          &lt;tab&gt; &lt;table&gt; &lt;tabl&gt; &lt;tab&gt; &lt;table&gt; &lt;tab&gt; &lt;tabl&gt;
1 heart_rate                     0      74.0    85.0   87.…  99.0      9…   1   
2 non_invasive_blood_pressure_s… 0     106.0   122.0  123.… 139.0    122… 669   
3 non_invasive_blood_pressure_m… 0      70.0    81.0   87.…  93.0   1401… 690   
4 respiratory_rate               0      15.0    18.0   18.…  22.0      1…  48   
5 temperature_fahrenheit         0      97.6    98.1   98.…  98.7      1… 940   
# … with abbreviated variable names ¹​`1st Qu.`, ²​`3rd Qu.`</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>chartevents_tble <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="sc">!</span>subject_id,</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"vital_measure"</span>,</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"value"</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(vital_measure) <span class="sc">%&gt;%</span> </span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> vital_measure, <span class="at">y =</span> value, <span class="at">color =</span> vital_measure)) <span class="sc">+</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>, <span class="at">na.rm =</span> T, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_colorblind</span>() <span class="sc">+</span> </span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">200</span>)) <span class="sc">+</span> </span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Vital measurements"</span>,</span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Value"</span></span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb65-16"><a href="#cb65-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb65-17"><a href="#cb65-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Similar as Q6.4, the outliers were hidden and the limit of <code>value</code> axis was set to an arbitrary number (200) in order to make the plot more readable.</p>
</section>
<section id="q7.-putting-things-together" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="q7.-putting-things-together"><span class="header-section-number">7</span> Q7. Putting things together</h2>
<p>Let us create a tibble <code>mimic_icu_cohort</code> for all ICU stays, where rows are the first ICU stay of each unique adult (age at admission &gt; 18) and columns contain at least following variables</p>
<ul>
<li>all variables in <code>icustays.csv.gz</code><br>
</li>
<li>all variables in <code>admission.csv.gz</code><br>
</li>
<li>all variables in <code>patients.csv.gz</code><br>
</li>
<li>first lab measurements during ICU stay<br>
</li>
<li>first vital measurements during ICU stay</li>
<li>an indicator variable <code>thirty_day_mort</code> whether the patient died within 30 days of hospital admission (30 day mortality)</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>mimic_icu_cohort <span class="ot">&lt;-</span> <span class="fu">list</span>(icustays_tble, admissions_tble, </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>                         patients_tble, labevents_tble, </span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>                         chartevents_tble) <span class="sc">%&gt;%</span> </span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">reduce</span>(left_join, <span class="at">by =</span> <span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span> <span class="co">#apply left_join multiple times to the given list</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(anchor_age <span class="sc">&gt;</span> <span class="dv">18</span>) <span class="sc">%&gt;%</span> <span class="co">#limit to age &gt; 18</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">thirty_day_mort =</span> <span class="fu">if_else</span>(<span class="sc">!</span><span class="fu">is.na</span>(deathtime) <span class="sc">&amp;</span> lengthstay <span class="sc">&lt;=</span> <span class="dv">30</span>, <span class="st">"Died within 30 days"</span>, <span class="st">"Didn't die within 30 days"</span>)) <span class="sc">%&gt;%</span> <span class="co">#create indicator variable</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.character, str_to_title) <span class="sc">%&gt;%</span> <span class="co">#change all strings to title style</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">vars</span>(thirty_day_mort), fct_rev) <span class="sc">%&gt;%</span> <span class="co">#revert factor level</span></span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,055 × 41
   subject_id  hadm_id  stay_id first_careunit                                  
        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;                                           
 1   10000032 29079034 39553978 Medical Intensive Care Unit (Micu)              
 2   10000980 26913865 39765666 Medical Intensive Care Unit (Micu)              
 3   10001217 24597018 37067082 Surgical Intensive Care Unit (Sicu)             
 4   10001725 25563031 31205490 Medical/Surgical Intensive Care Unit (Micu/Sicu)
 5   10001884 26184834 37510196 Medical Intensive Care Unit (Micu)              
 6   10002013 23581541 39060235 Cardiac Vascular Intensive Care Unit (Cvicu)    
 7   10002155 23822395 33685454 Coronary Care Unit (Ccu)                        
 8   10002223 22494570 39638202 Trauma Sicu (Tsicu)                             
 9   10002348 22725460 32610785 Neuro Intermediate                              
10   10002428 28662225 33987268 Medical Intensive Care Unit (Micu)              
   last_careunit                                    intime             
   &lt;chr&gt;                                            &lt;dttm&gt;             
 1 Medical Intensive Care Unit (Micu)               2180-07-23 14:00:00
 2 Medical Intensive Care Unit (Micu)               2189-06-27 08:42:00
 3 Surgical Intensive Care Unit (Sicu)              2157-11-20 19:18:02
 4 Medical/Surgical Intensive Care Unit (Micu/Sicu) 2110-04-11 15:52:22
 5 Medical Intensive Care Unit (Micu)               2131-01-11 04:20:05
 6 Cardiac Vascular Intensive Care Unit (Cvicu)     2160-05-18 10:00:53
 7 Coronary Care Unit (Ccu)                         2129-08-04 12:45:00
 8 Trauma Sicu (Tsicu)                              2158-01-15 08:01:49
 9 Neuro Intermediate                               2112-11-30 23:24:00
10 Medical Intensive Care Unit (Micu)               2156-04-12 16:24:18
   outtime               los admittime           dischtime          
   &lt;dttm&gt;              &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;             
 1 2180-07-23 23:50:47 0.410 2180-07-23 12:35:00 2180-07-25 17:55:00
 2 2189-06-27 20:38:27 0.498 2189-06-27 07:38:00 2189-07-03 03:00:00
 3 2157-11-21 22:08:00 1.12  2157-11-18 22:56:00 2157-11-25 18:00:00
 4 2110-04-12 23:59:56 1.34  2110-04-11 15:08:00 2110-04-14 15:00:00
 5 2131-01-20 08:27:30 9.17  2131-01-07 20:39:00 2131-01-20 05:15:00
 6 2160-05-19 17:33:33 1.31  2160-05-18 07:45:00 2160-05-23 13:30:00
 7 2129-08-10 17:02:38 6.18  2129-08-04 12:44:00 2129-08-18 16:53:00
 8 2158-01-16 15:19:24 1.30  2158-01-15 08:00:00 2158-01-20 19:29:00
 9 2112-12-10 18:25:13 9.79  2112-11-30 22:22:00 2112-12-10 17:56:00
10 2156-04-17 15:57:08 4.98  2156-04-12 14:16:00 2156-04-29 16:26:00
   deathtime           admission_type              admission_location    
   &lt;dttm&gt;              &lt;chr&gt;                       &lt;chr&gt;                 
 1 NA                  Ew Emer.                    Emergency Room        
 2 NA                  Ew Emer.                    Emergency Room        
 3 NA                  Ew Emer.                    Emergency Room        
 4 NA                  Ew Emer.                    Pacu                  
 5 2131-01-20 05:15:00 Observation Admit           Emergency Room        
 6 NA                  Surgical Same Day Admission Physician Referral    
 7 NA                  Ew Emer.                    Procedure Site        
 8 NA                  Ew Emer.                    Emergency Room        
 9 NA                  Observation Admit           Transfer From Hospital
10 NA                  Ew Emer.                    Emergency Room        
   discharge_location           insurance language marital_status
   &lt;chr&gt;                        &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;         
 1 Home                         Medicaid  English  Widowed       
 2 Home Health Care             Medicare  English  Married       
 3 Home Health Care             Other     ?        Married       
 4 Home                         Other     English  Married       
 5 Died                         Medicare  English  Married       
 6 Home Health Care             Medicare  English  Single        
 7 Chronic/Long Term Acute Care Other     English  Married       
 8 Home                         Other     English  &lt;NA&gt;          
 9 Home Health Care             Medicare  English  Single        
10 Skilled Nursing Facility     Medicare  English  Widowed       
   ethnicity              edregtime           edouttime          
   &lt;chr&gt;                  &lt;dttm&gt;              &lt;dttm&gt;             
 1 White                  2180-07-23 05:54:00 2180-07-23 14:00:00
 2 Black/African American 2189-06-27 06:25:00 2189-06-27 08:42:00
 3 White                  2157-11-18 17:38:00 2157-11-19 01:24:00
 4 White                  NA                  NA                 
 5 Black/African American 2131-01-07 13:36:00 2131-01-07 22:13:00
 6 Other                  NA                  NA                 
 7 White                  2129-08-04 11:00:00 2129-08-04 12:35:00
 8 Unable To Obtain       2158-01-15 06:49:00 2158-01-15 07:36:00
 9 White                  2112-11-30 15:08:00 2112-11-30 23:24:00
10 White                  2156-04-12 09:56:00 2156-04-12 17:11:00
   hospital_expire_flag lengthstay        gender anchor_age anchor_year
                  &lt;dbl&gt; &lt;Duration&gt;        &lt;chr&gt;       &lt;dbl&gt;       &lt;dbl&gt;
 1                    0 2.22222222222222s Female         52        2180
 2                    0 5.80694444444444s Female         73        2186
 3                    0 6.79444444444444s Female         55        2157
 4                    0 2.99444444444444s Female         46        2110
 5                    1 12.3583333333333s Female         68        2122
 6                    0 5.23958333333333s Female         53        2156
 7                    0 14.1729166666667s Female         80        2128
 8                    0 5.47847222222222s Male           21        2158
 9                    0 9.81527777777778s Female         77        2112
10                    0 17.0902777777778s Female         80        2155
   anchor_year_group dod        bicarbonate chloride creatinine glucose
   &lt;chr&gt;             &lt;date&gt;           &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
 1 2014 - 2016       NA                  21      102        0.5     115
 2 2008 - 2010       NA                  NA       NA       NA        NA
 3 2011 - 2013       NA                  23      104        0.4     113
 4 2011 - 2013       NA                  24      106        0.8     146
 5 2008 - 2010       2131-01-20          33       96        1.1     148
 6 2008 - 2010       NA                  23      109        1.1      98
 7 2008 - 2010       2131-03-10          25      106        0.9      95
 8 2008 - 2010       NA                  26      102        0.8      88
 9 2017 - 2019       NA                  23      107        0.8     127
10 2011 - 2013       NA                  20       98        0.8      99
   potassium sodium hematocrit white_blood_cells heart_rate
       &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;             &lt;dbl&gt;      &lt;dbl&gt;
 1       4.7    132       NA                NA           91
 2      NA       NA       NA                NA           77
 3       3.6    138       33.6              19           86
 4       3.9    140       39.1              17           55
 5       4      136       36                18.4         38
 6       4      140       28.6              18.2         80
 7       4.5    139       37.9               5.5         68
 8       3.9    138       32.5              10.1        100
 9       4.8    142       39.3               4.3         72
10       3.9    129       28.7              22.4        124
   non_invasive_blood_pressure_systolic non_invasive_blood_pressure_mean
                                  &lt;dbl&gt;                            &lt;dbl&gt;
 1                                   84                               56
 2                                  150                               92
 3                                  151                              104
 4                                   73                               59
 5                                  180                               46
 6                                  104                               77
 7                                  126                               78
 8                                  123                               80
 9                                  129                               85
10                                   87                               53
   respiratory_rate temperature_fahrenheit thirty_day_mort          
              &lt;dbl&gt;                  &lt;dbl&gt; &lt;fct&gt;                    
 1               24                   98.7 Didn't Die Within 30 Days
 2               23                   98   Didn't Die Within 30 Days
 3               18                   98.5 Didn't Die Within 30 Days
 4               19                   97.7 Didn't Die Within 30 Days
 5               10                   98.1 Died Within 30 Days      
 6               14                   97.2 Didn't Die Within 30 Days
 7               18                   95.9 Didn't Die Within 30 Days
 8               29                   98.6 Didn't Die Within 30 Days
 9               14                   97.9 Didn't Die Within 30 Days
10               25                  103.  Didn't Die Within 30 Days
# … with 53,045 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mimic_icu_cohort<span class="sc">$</span>thirty_day_mort)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Died Within 30 Days Didn't Die Within 30 Days 
                     5210                     47845 </code></pre>
</div>
</div>
</section>
<section id="q8.-exploratory-data-analysis-eda" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="q8.-exploratory-data-analysis-eda"><span class="header-section-number">8</span> Q8. Exploratory data analysis (EDA)</h2>
<p>Summarize following information using appropriate numerics or graphs.</p>
<ul>
<li><p><code>thirty_day_mort</code> vs demographic variables (ethnicity, language, insurance, marital_status, gender, age at hospital admission)</p></li>
<li><p><code>thirty_day_mort</code> vs first lab measurements</p></li>
<li><p><code>thirty_day_mort</code> vs first vital measurements</p></li>
<li><p><code>thirty_day_mort</code> vs first ICU unit</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># `thirty_day_mort` vs demographic variables</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="co"># iteration of ggplots (categorical variables)</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(<span class="st">"ethnicity"</span>, <span class="st">"language"</span>, <span class="st">"insurance"</span>, </span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>     <span class="st">"marital_status"</span>, <span class="st">"gender"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span>mimic_icu_cohort <span class="sc">%&gt;%</span> </span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggplot</span>(</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>(</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> .data[[.x]], </span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">fill =</span> thirty_day_mort</span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>          )</span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>        ) <span class="sc">+</span> </span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">scale_fill_colorblind</span>() <span class="sc">+</span> </span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(</span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span> .x,  </span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"Number of subjects"</span>, </span>
<span id="cb70-19"><a href="#cb70-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">fill =</span> <span class="st">"30 day mortality"</span></span>
<span id="cb70-20"><a href="#cb70-20" aria-hidden="true" tabindex="-1"></a>        ) <span class="sc">+</span> </span>
<span id="cb70-21"><a href="#cb70-21" aria-hidden="true" tabindex="-1"></a>      <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb70-22"><a href="#cb70-22" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_classic</span>()</span>
<span id="cb70-23"><a href="#cb70-23" aria-hidden="true" tabindex="-1"></a>      )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-34-2.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-34-3.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-34-4.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[5]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-34-5.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ggplot of numeric variable (age at admission)</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>mimic_icu_cohort <span class="sc">%&gt;%</span> </span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> thirty_day_mort, </span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> anchor_age, </span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">color =</span> thirty_day_mort</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span> </span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">na.rm =</span> T, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_colorblind</span>() <span class="sc">+</span></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"30 day mortality"</span>,</span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Age at admission"</span></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-34-6.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># `thirty_day_mort` vs first lab measurements</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="co">#create a function to remove outliers</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>dec_out_na <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">thres =</span> <span class="dv">3</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) {</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>  sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(x, <span class="at">na.rm =</span> na.rm)</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>  mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(x, <span class="at">na.rm =</span> na.rm)</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>  id_out <span class="ot">=</span> x <span class="sc">&gt;</span> mean <span class="sc">+</span> thres <span class="sc">*</span> sd <span class="sc">|</span> x <span class="sc">&lt;</span> mean <span class="sc">-</span> thres <span class="sc">*</span> sd</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>  x[id_out] <span class="ot">=</span> <span class="cn">NA</span></span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(x)</span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>dlabitems_tble <span class="sc">%&gt;%</span> </span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(label) <span class="sc">%&gt;%</span> </span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_to_lower</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_replace_all</span>(<span class="st">" "</span>, <span class="st">"_"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb77-16"><a href="#cb77-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(</span>
<span id="cb77-17"><a href="#cb77-17" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span>mimic_icu_cohort <span class="sc">%&gt;%</span> </span>
<span id="cb77-18"><a href="#cb77-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate_if</span>(is.numeric, dec_out_na) <span class="sc">%&gt;%</span> </span>
<span id="cb77-19"><a href="#cb77-19" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggplot</span>(</span>
<span id="cb77-20"><a href="#cb77-20" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>(</span>
<span id="cb77-21"><a href="#cb77-21" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> thirty_day_mort, </span>
<span id="cb77-22"><a href="#cb77-22" aria-hidden="true" tabindex="-1"></a>          <span class="at">y =</span> .data[[.x]], </span>
<span id="cb77-23"><a href="#cb77-23" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> thirty_day_mort</span>
<span id="cb77-24"><a href="#cb77-24" aria-hidden="true" tabindex="-1"></a>          )</span>
<span id="cb77-25"><a href="#cb77-25" aria-hidden="true" tabindex="-1"></a>        ) <span class="sc">+</span> </span>
<span id="cb77-26"><a href="#cb77-26" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_boxplot</span>(<span class="at">na.rm =</span> T, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb77-27"><a href="#cb77-27" aria-hidden="true" tabindex="-1"></a>        <span class="fu">scale_color_colorblind</span>() <span class="sc">+</span> </span>
<span id="cb77-28"><a href="#cb77-28" aria-hidden="true" tabindex="-1"></a>        <span class="fu">labs</span>(</span>
<span id="cb77-29"><a href="#cb77-29" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="st">"30 day mortality"</span>, </span>
<span id="cb77-30"><a href="#cb77-30" aria-hidden="true" tabindex="-1"></a>          <span class="at">y =</span> .x</span>
<span id="cb77-31"><a href="#cb77-31" aria-hidden="true" tabindex="-1"></a>          ) <span class="sc">+</span> </span>
<span id="cb77-32"><a href="#cb77-32" aria-hidden="true" tabindex="-1"></a>        <span class="fu">theme_classic</span>()</span>
<span id="cb77-33"><a href="#cb77-33" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-35-2.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-35-3.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-35-4.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[5]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-35-5.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[6]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-35-6.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[7]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-35-7.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[8]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-35-8.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>I created a function to remove all extreme values in lab measurements so that the boxplots were more readable.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># `thirty_day_mort` vs first vital measurements</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>dchartitems_tble <span class="sc">%&gt;%</span> </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(label) <span class="sc">%&gt;%</span> </span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_to_lower</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_replace_all</span>(<span class="st">" "</span>, <span class="st">"_"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(</span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span>mimic_icu_cohort <span class="sc">%&gt;%</span> </span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate_if</span>(is.numeric, dec_out_na) <span class="sc">%&gt;%</span> </span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(.data[[.x]] <span class="sc">&lt;</span> <span class="dv">300</span>) <span class="sc">%&gt;%</span></span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggplot</span>(</span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>(</span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> thirty_day_mort, </span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">y =</span> .data[[.x]], </span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> thirty_day_mort</span>
<span id="cb86-15"><a href="#cb86-15" aria-hidden="true" tabindex="-1"></a>          )</span>
<span id="cb86-16"><a href="#cb86-16" aria-hidden="true" tabindex="-1"></a>        ) <span class="sc">+</span> </span>
<span id="cb86-17"><a href="#cb86-17" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_boxplot</span>(<span class="at">na.rm =</span> T, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb86-18"><a href="#cb86-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">scale_color_colorblind</span>() <span class="sc">+</span> </span>
<span id="cb86-19"><a href="#cb86-19" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(</span>
<span id="cb86-20"><a href="#cb86-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span> <span class="st">"30 day mortality"</span>, </span>
<span id="cb86-21"><a href="#cb86-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> .x</span>
<span id="cb86-22"><a href="#cb86-22" aria-hidden="true" tabindex="-1"></a>        ) <span class="sc">+</span> </span>
<span id="cb86-23"><a href="#cb86-23" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_classic</span>()</span>
<span id="cb86-24"><a href="#cb86-24" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-36-2.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-36-3.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-36-4.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[5]]</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-36-5.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>To visualize the vital measurements, I also applied the same function to remove outliers. However, some extreme data points were not removed since the maximum value of some variables are too large so that these values did not meet the criteria of “outliers” (i.e., within 3 standard deviations around the mean). Therefore, I further set an arbitrary cutoff (300) to keep values that make biological sense.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># `thirty_day_mort` vs first ICU unit</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>mimic_icu_cohort <span class="sc">%&gt;%</span> </span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> first_careunit, <span class="at">fill =</span> thirty_day_mort)) <span class="sc">+</span> </span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_colorblind</span>() <span class="sc">+</span> </span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"First ICU unit"</span>, </span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of subjects"</span>, </span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"30 day mortality"</span></span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span> </span>
<span id="cb92-11"><a href="#cb92-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb92-12"><a href="#cb92-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>